
  on:
    push:
      branches:
        - master




  jobs:
    build:
      runs-on:  ubuntu-latest
      
      steps:
        - name: 'before'
          run: ls
        
        - name:  'actions/checkout@v3'
        
        - name: 'after1'
          run: ls
       

